### ISSUE TITLE
None of the tasks are being displayed on Open Tasks

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#11]
**Describe the bug**
Tasks are missing

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/47746685-f1679700-dc5c-11e8-8f0f-101065fa3967.png)

**Comment by saracope** [comment]
I'm seeing this now. May have been resolved already. Can you confirm you still have this issue @jlow81?

**Comment by jlow81** [comment]
Its working now, thanks.

**Comment by saracope** [comment]
Ok, closing out.
