### ISSUE TITLE
When user clicks off of the main navigation, the navigation should return to default state

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#13]
**Describe the bug**
When user clicks off of the main navigation, the nav should return to default state.  Also, if a new page is loaded the nav should go back to its default state.

**To Reproduce**
1. Click on nav item
2. Click elsewhere on the screen
3. The nav stays visible

**Expected behavior**
Nav should hide

**Comment by DanielJDufour** [comment]
@jlow81 , I'll write code to hide the menu when switch pages, but we'll have to do clicking off to hide the menu after the migration (it's currently not a feature on the live production site)

**Comment by DanielJDufour** [comment]
I'm working on hiding nav when change pages

**Comment by DanielJDufour** [comment]
Fixed
