### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#16]
**Describe the bug**
Update the roadmap to the following:

Mark Phase 1 SEO as released
Mark Search Scoring Phase 1 as released
Mark Update Search Filters as released
Mark Update Open Tasks Phase 1 as released
Mark Update UI for Search Results as released
Mark Usability Sessions, Round 2 as released

Remove States and Cities Pilot Program

**Comment by DanielJDufour** [comment]
Done
