### ISSUE TITLE
On mobile, result card alignment is all messed up

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#21]
**Describe the bug**
The content in a result card is a bit of a mess.  Specifically the languages.  Its hard to read.  Can we separate by commas at the very least and start it in line with the language title like everything else?  And the space between last update and usage type is larger than the rest.  Lastly, do you know why #nsacyber is showing up in the description?

This is on iPhone X iOS 12

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/47798333-8c647d80-dcfe-11e8-8d88-8a123a2491fc.png)

**Comment by saracope** [comment]
This was fixed by a PR on the style repo so will update when that is pushed.
Note: the #nsacyber hashtag is one that these projects include in their description.
