### ISSUE TITLE
Filter tags are not being displayed

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#29]
**Describe the bug**
When I click a filter the corresponding tag is not displaying

**Screenshots**
Live site
![image](https://user-images.githubusercontent.com/29412125/47870335-b0e45680-dddf-11e8-855b-e59d1492f742.png)

React site
![image](https://user-images.githubusercontent.com/29412125/47870347-bb9eeb80-dddf-11e8-82ec-db283a364d4c.png)

**Comment by DanielJDufour** [comment]
I'll do this today

**Comment by saracope** [comment]
It looks like this fix was implemented by @DanielJDufour, closing out.
