### ISSUE TITLE
Typing URL for staging.code.gov/open-tasks does not work

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#32]
**Describe the bug**
If I type in the URL https://staging.code.gov/open-tasks I get a 404 page, but if I click on Open Tasks from the nav it works

**To Reproduce**
1. Type 'https://staging.code.gov/open-tasks' into browser
2. See 404 page

**Expected behavior**
Should take me to Open Tasks page

**Comment by DanielJDufour** [comment]
fixed.

**Comment by DanielJDufour** [comment]
I'll need to ask Federalist to deploy the same 404 file to production, too
