### ISSUE TITLE
Open Tasks filters not working

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#33]
**Describe the bug**
When I select a filter on the Open Tasks page, nothing changes

**To Reproduce**
1. Go to Open Tasks page
2. Click on a filter

**Expected behavior**
Tasks should update based on selected filter

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/48020584-45162c80-e104-11e8-957e-5d2754052a21.png)

**Comment by DanielJDufour** [comment]
I'll take this

**Comment by DanielJDufour** [comment]
@jlow81 , I just fixed this. Please QA on staging.code.gov. Thanks!
