### ISSUE TITLE
Policy page - Space needed between end of body content and footer

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#39]
**Describe the bug**
There should be some space between the end of the body content and the footer (I noticed this while reviewing the policy page).

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/48140358-95150080-e276-11e8-996e-7f408d37426c.png)

**Comment by DanielJDufour** [comment]
I'll take this

**Comment by DanielJDufour** [comment]
Fixed

**Comment by jlow81** [comment]
Can you please apply this same fix to all of the about sections?  Thanks.

**Comment by DanielJDufour** [comment]
Okay. I just added padding at the bottom for the about pages.
