### ISSUE TITLE
Featured Projects images on wrong side

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#4]
**Describe the bug**
Image for first and third featured projects should be on the left side

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/47744527-e3634780-dc57-11e8-8a20-f1cd51e774a8.png)

**Comment by DanielJDufour** [comment]
@saracope , could you take a look at this as you are working on the home page. Thanks!

**Comment by saracope** [comment]
In the [home-featured-project component](https://github.com/GSA/caribou/blob/1774ef725da06759cd97a6a9bac453a4dc0297d1/src/components/home-featured-project/home-featured-project.component.js#L6) it looks like `index` here is undefined, so `place ==='even'` on line 14 doesn't ever evaluate to true. This is what switches the layout so the pic is on the left.
