### ISSUE TITLE
On mobile, policy page navigation should be put in dropdown

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#43]
**Describe the bug**
Instead of listing all of the subpage options out, they should be placed in a dropdown so as not to push the main content down too far.

![legacy_policy_mobile](https://user-images.githubusercontent.com/29412125/48143515-f049f180-e27c-11e8-97f1-c12e81defb0a.png)

**Comment by DanielJDufour** [comment]
I'll take this

**Comment by DanielJDufour** [comment]
Done
