### ISSUE TITLE
Make Navigation in About Section Better

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/caribou#49]
**Describe the bug**
Navigation in the FSCP Policy Page uses a dropdown while about page uses a multi-level list.  @jlow81 , should I convert the about section navigation to a dropdown?

**To Reproduce**
1. Go to staging.code.gov/about

**Expected behavior**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/4313463/48385616-26dc9d80-e6bd-11e8-8bf4-e4f42d423d88.png)

**Additional context**

**Comment by jlow81** [comment]
@DanielJDufour Yes, the about section should be converted to a dropdown for mobile.  Thanks.

**Comment by DanielJDufour** [comment]
@jlow81 , should I use dashes to delineate the hierarchy? like
Overview - Introduction
Overview - Tracking Progress
Compliance - Agency Compliance

**Comment by DanielJDufour** [comment]
Done. I converted to a dropdown.
![image](https://user-images.githubusercontent.com/4313463/48465058-99c64100-e7af-11e8-8c20-f1ad530467ee.png)
Please reopen or create another issue if you want what I did changed
