### ISSUE TITLE
On Mobile, when nav is open the close button is missing

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#51]
![image](https://user-images.githubusercontent.com/29412125/48390046-2e587280-e6ce-11e8-895f-3317d1592b1e.png)

**Comment by DanielJDufour** [comment]
@jlow81 , I'm having trouble replicating this issue.  It works fine on my Samsung Galaxy S5 on Chrome and Firefox.  Did you test on Safari?

**Comment by jlow81** [comment]
@DanielJDufour I am on safari on my iPhone X and still having the issue.  There is no close button being displayed on the mobile menu

**Comment by DanielJDufour** [comment]
Fixed
