### ISSUE TITLE
Dropdown menus on Browse Projects and Search Results are too narrow

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#54]
**Describe the bug**
The dropdowns should be taller

![image](https://user-images.githubusercontent.com/29412125/48421420-73aa8d80-e72a-11e8-89dd-d9839fc1b29a.png)

**Comment by DanielJDufour** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/4313463/48462253-70a0b300-e7a5-11e8-9a15-b3eeb8e059f1.png)

Please reopen if still an issue on MacOS/Safari. Thanks!
