### ISSUE TITLE
When nav is expanded the Code.gov logo gets pushed down, it should stay at the top

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#57]
![image](https://user-images.githubusercontent.com/29412125/48422139-01d34380-e72c-11e8-9c98-d753815de6fc.png)

**Comment by DanielJDufour** [comment]
I fixed this late last night. Could you refresh your cache and try again?  If it's still an issue, feel free to reopen the issue.
![image](https://user-images.githubusercontent.com/4313463/48436445-a9f90480-e74c-11e8-9fcd-1dc23212c690.png)
