### ISSUE TITLE
Padding needed between tags on Project Details page

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#58]
![image](https://user-images.githubusercontent.com/29412125/48424120-f550ea00-e72f-11e8-8f70-9ca5040fa31e.png)

**Comment by DanielJDufour** [comment]
@jlow81 , I think this was fixed today. Could you confirm either way?  If fixed, please close issue.
![image](https://user-images.githubusercontent.com/4313463/48460873-04bb4c00-e79f-11e8-995e-967b3207db97.png)

**Comment by DanielJDufour** [comment]
Closing. Please reopen if still an issue
