### ISSUE TITLE
Metadata on Project Details page should be left aligned with rest of content

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#61]
![image](https://user-images.githubusercontent.com/29412125/48424769-5200d480-e731-11e8-8fff-f1b5670247b7.png)

**Comment by DanielJDufour** [comment]
I can confirm this is an issue on production, too:
https://code.gov/#!/explore-code/agencies/NARA/repos/nara_national_archives_records_administration_fr2_blog
![image](https://user-images.githubusercontent.com/4313463/48425224-5e396180-e732-11e8-9bc7-3d0564fd5579.png)

**Comment by DanielJDufour** [comment]
Complete
