### ISSUE TITLE
Need space between Hide Option fields and table on How to Inventory Code

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#64]
![image](https://user-images.githubusercontent.com/29412125/48428737-9d1ee580-e739-11e8-80e3-bfe816126ac4.png)

**Comment by DanielJDufour** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/4313463/48436890-e6793000-e74d-11e8-8c1d-4d0b66c79c2a.png)

https://staging.code.gov/about/compliance/inventory-code
