### ISSUE TITLE
On mobile and tablet, 'X' missing on filter tags

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#66]
![image](https://user-images.githubusercontent.com/29412125/48437334-1117b880-e74f-11e8-99e3-3902035c0da1.png)

![image](https://user-images.githubusercontent.com/29412125/48437339-16750300-e74f-11e8-9d0d-b01e22bd475c.png)

**Comment by DanielJDufour** [comment]
I'm assuming this is a difference in browser support. Will investigate further

**Comment by DanielJDufour** [comment]
Issues looks like that some browsers don't support background-image values that use a dataurl to a svg like
`background-image: url(data:image/svg+xml;utf8,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20w…2%202.283-3.37%202.283-5.54%200-2.174-.76-4.02-2.28-5.54z%22/%3E%3C/svg%3E);`

**Comment by DanielJDufour** [comment]
I spoke with a community member who will try to implement this. If they can't get it done by Friday, I'll take care of it over the weekend.

**Comment by DanielJDufour** [comment]
Fixed.

**Comment by jlow81** [comment]
This is still an issue.  I'm an iPad 4th Gen iOS 10

![image](https://user-images.githubusercontent.com/29412125/48563164-afc42680-e8c1-11e8-89d8-b83e17a0ccd4.png)

**Comment by DanielJDufour** [comment]
I just submitted a fix.  Could you check and see if that worked?

**Comment by jlow81** [comment]
works now, thanks.
