### ISSUE TITLE
Overflow of text in the Side Bar 

### ISSUE THREAD

**Issue by BalajiJBcs** [GSA/caribou#70]
**Describe the bug**
Browse Project sidebar have an overflow issue, in which the text overflow the div box.

**To Reproduce**
1. Go to 'index->Browse Project'
2. Click on 'Browse Project'
3. Scroll down to  or Navigate 'Federal Agency and License'

**Expected behavior**
Should align and wrap the text inside the div.

**Screenshots**
![screenshot 7](https://user-images.githubusercontent.com/31539453/48459255-7fac5300-e7ef-11e8-9842-c5a95defc17f.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser Chrome
 - Version

**Comment by DanielJDufour** [comment]
@BalajiJBcs , I think I fixed this in https://github.com/GSA/code-gov-style/commit/14306c33bc17d195da95a16354ef6074e3b9d5cc, but I didn't add to master for this project yet.  I'm updating that now.

**Comment by DanielJDufour** [comment]
Thanks for the catch!

**Comment by DanielJDufour** [comment]
Could you re-reun `npm install` and see if that fixes the problem?

**Comment by DanielJDufour** [comment]
Here's a link to our hosted demo version on style guide: https://gsa.github.io/code-gov-style/components/filter

**Comment by BalajiJBcs** [comment]
@DanielJDufour The issue is resolved and works fine. I have tested in dev environment. Your patch works. :)

**Comment by DanielJDufour** [comment]
Thanks!! :-)
