### ISSUE TITLE
Update Metadata Schema 2.0.0 Description on ReactJS Solution

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/caribou#74]
The new ReactJS Metadata Schema 2.0.0 content (field dentition) does not match the live website content. 

**To Reproduce**
1. Go to https://staging.code.gov/about/compliance/inventory-code
2.  Review the content. 
3. Compare to the live (production) website content: https://www.code.gov/#!/policy-guide/docs/compliance/inventory-code
4. Field definitions do not match. 

**Expected behavior**
The Metadata Schema 2.0.0 field definitions should match. 

**Screenshots**
Live Website (Production): 
![screen shot 2018-11-14 at 10 47 20 am](https://user-images.githubusercontent.com/2433138/48498410-39adba00-e804-11e8-863e-a7633888dac6.png)

Staging: 
![screen shot 2018-11-14 at 10 47 29 am](https://user-images.githubusercontent.com/2433138/48498435-43372200-e804-11e8-8752-43b74327e647.png)

**Comment by DanielJDufour** [comment]
Technically, fixed
![image](https://user-images.githubusercontent.com/4313463/48501091-5816b400-e80a-11e8-9da3-1b5bff37d198.png)


But it looks ugly.  I created an issue in the web component repo to convert it to bullets:
https://github.com/GSA/json-schema-web-component/issues/2
