### ISSUE TITLE
In breadcrumbs, there should be a space between the first item and '>'

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#76]
![image](https://user-images.githubusercontent.com/29412125/48500424-d5412980-e808-11e8-8a8c-26a7983c223d.png)

**Comment by DanielJDufour** [comment]
oof. fixing now

**Comment by DanielJDufour** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/4313463/48502008-91e8ba00-e80c-11e8-8a89-bf725373c214.png)
