### ISSUE TITLE
Searching by term results in filter options that yield zero results

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#78]
**Describe the bug**
I searched for 'water' and on the Search Results page I clicked on the language filter for Assembly and no results were found.

I thought we were only showing filters if there was an existing project?

![image](https://user-images.githubusercontent.com/29412125/48512450-80f97200-e827-11e8-9d46-2c39c67e57f4.png)

**Comment by jlow81** [comment]
Same thing happens with Agency Filter

![image](https://user-images.githubusercontent.com/29412125/48513074-e437d400-e828-11e8-873a-8ac774d2c0cf.png)

**Comment by jlow81** [comment]
And licenses

![image](https://user-images.githubusercontent.com/29412125/48513122-029dcf80-e829-11e8-98b6-e6e56321fa47.png)

**Comment by DanielJDufour** [comment]
Good catch. Your understanding is correct. I'll fix that.

**Comment by DanielJDufour** [comment]
Fixed
