### ISSUE TITLE
No predictive search

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#79]
Looks like we lost predictive search

**Live Site:**
![image](https://user-images.githubusercontent.com/29412125/48513204-3b3da900-e829-11e8-86a1-9b5e0c16a3bc.png)

**React Site:**
![image](https://user-images.githubusercontent.com/29412125/48513224-4690d480-e829-11e8-9d96-830128352cd0.png)

**Comment by DanielJDufour** [comment]
I deployed autocomplete to staging. Please QA. Thanks

**Comment by jlow81** [comment]
works now, thanks.
