### ISSUE TITLE
Pagination prev arrow pointing in wrong direction

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#83]
**Describe the bug**
When I click on 'Next' in pagination the arrow next to 'Prev' is pointing up and should be pointing to the left.  This occurs on any page with pagination.

![image](https://user-images.githubusercontent.com/29412125/48647931-88ea1b00-e9bb-11e8-87ba-441e65bae4d5.png)

![image](https://user-images.githubusercontent.com/29412125/48648012-c3ec4e80-e9bb-11e8-8a06-4b5393bc12a4.png)

**Comment by DanielJDufour** [comment]
@jlow81 , I agree. I think it should continue pointing to the left.  Pointing up is currently the way that it happens on the Angular version (and was intentionally code that way by someone), so I assumed that is the way you wanted it on React.  I'm backlogging this, but happy to change this after the migration.

**Comment by DanielJDufour** [comment]
Fixed
