### ISSUE TITLE
Autocomplete recommendations list does not go away after I click off/away

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#85]
**Describe the bug**
When I start typing in a search term I get the autocomplete recommendations.  If I click off/away from the autocomplete recommendations they don't go away which blocks the language filter.  On the live site this is not an issue.

Live site:
![autocomplete_live](https://user-images.githubusercontent.com/29412125/48648412-3d387100-e9bd-11e8-9bbe-29a52e124028.gif)

React site:
![autocomplete_react](https://user-images.githubusercontent.com/29412125/48648421-46294280-e9bd-11e8-8154-29acf771d0fe.gif)

**Comment by DanielJDufour** [comment]
Fixed. Thanks for catching this :-)
