### ISSUE TITLE
Last updated date should not be bold

### ISSUE THREAD

**Issue by jlow81** [GSA/caribou#9]
**Describe the bug**
Last updated date should not be bold

**Screenshots**
![image](https://user-images.githubusercontent.com/29412125/47746383-5bcc0780-dc5c-11e8-8661-4c58a87669b3.png)

**Comment by DanielJDufour** [comment]
I don't see this issue on my computer or smart phone.  It could be an iOS thing and the way that it renders `dd` elements.  @saracope , could you take a look? 

https://github.com/GSA/code-gov-style/blob/8bbc740683dfd5b8c0ff5445d2fb06e8fa826151/_sass/_cards.scss#L114

**Comment by saracope** [comment]
I'm not seeing this in chrome or firefox. 
@jlow81 Can you give more detail about the system setup you're seeing this on?

**Comment by jlow81** [comment]
Seems to have been fixed, although now the spacing is all jacked up

![image](https://user-images.githubusercontent.com/29412125/47801146-efa4de80-dd03-11e8-81e0-c90cccf4254a.png)

**Comment by saracope** [comment]
@jlow81 Closing this one out. Please put in a new issue for the spacing issue.
